// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// Load .env.local first (Next.js convention), then .env
config({ path: ".env.local" });
config();
import { defineConfig } from "prisma/config";

// Supabase requires SSL; ensure sslmode is present
function ensureSupabaseSsl(url: string | undefined): string | undefined {
  if (!url || !url.includes("supabase")) return url;
  if (url.includes("sslmode=")) return url;
  const sep = url.includes("?") ? "&" : "?";
  return `${url}${sep}sslmode=require`;
}

const databaseUrl = ensureSupabaseSsl(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
